### ISSUE TITLE
South Africa is overwritten by Saudi Arabia

### ISSUE THREAD

**Issue by productiveme** [mitica/public-holidays-js#1]
Greetings, 

The country for South Africa is (unfortunately) `sa` and since this is listed as an override in `countries.json` as `sa: saudiarabian`, it means South African holidays cannot be pulled down with the package. I need to remove the line from countries.json in order to pull down the holidays I want. Could you perhaps do a method which allows the country exactly as specified, or a flag or something?

**Comment by mitica** [comment]
Hi,

I guess you need to use [za](https://en.wikipedia.org/wiki/ISO_3166-2:ZA) for South Africa, and `sa` for Saudi Arabia.

**Comment by productiveme** [comment]
H @Mitica,

I checked and sadly its not the case, South African holidays are at en.sa#holiday@group.v.calendar.google.com, while the en.saudiarabian#holiday@group.v.calendar.google.com url seems to work for the Saudi Arabian holiday calendar.

**Comment by mitica** [comment]
Hi @productiveme,

Hope I fixed #1. Added a new country code map: `za`: `sa`
