### ISSUE TITLE
Incompatibility with React Native

### ISSUE THREAD

**Issue by JesusTheHun** [mitica/public-holidays-js#2]
I tried to use this lib for a React Native app.
I end up with this error : 

`error: bundling failed: Error: Unable to resolve module 'fs' from '/Users/Marc/paprecAndClic/node_modules/ical/node-ical.js': Module 'fs' does not exist in the Haste module map`

The dependency `ical` you use in `fetch-holidays.ts` is responsible of this error. Can you substitute it to fix this error please ?

**Comment by marc-wilson** [comment]
Also incompatible with Angular v 7.2.1

I immediately got 7 npm audit errors when I installed it (I had 0 originally)

WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ical/node_modules/node-uuid/uuid.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/node-uuid'

WARNING in ./node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/bl/node_modules/readable-stream/lib'

WARNING in ./node_modules/bl/node_modules/readable-stream/lib/_stream_writable.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/bl/node_modules/readable-stream/lib'

ERROR in ./node_modules/aws4/aws4.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/aws4'
ERROR in ./node_modules/ecc-jsbn/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ecc-jsbn'
ERROR in ./node_modules/ical/node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/aws-sign2'
ERROR in ./node_modules/ical/node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/http-signature/lib'
ERROR in ./node_modules/ical/node_modules/http-signature/lib/verify.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/http-signature/lib'
ERROR in ./node_modules/ical/node_modules/oauth-sign/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/oauth-sign'
ERROR in ./node_modules/ical/node_modules/request/lib/helpers.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request/lib'
ERROR in ./node_modules/ical/node_modules/request/lib/oauth.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request/lib'
ERROR in ./node_modules/sshpk/lib/fingerprint.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/signature.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/utils.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/dhe.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/identity.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/certificate.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/private-key.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/key.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib/formats'
ERROR in ./node_modules/sshpk/lib/formats/pem.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib/formats'
ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
Module not found: Error: Can't resolve 'crypto' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib/formats'
ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/got'
ERROR in ./node_modules/ical/node-ical.js
Module not found: Error: Can't resolve 'fs' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical'
ERROR in ./node_modules/ical/node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request/lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'http' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/forever-agent'
ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'http' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/got'
ERROR in ./node_modules/got/errors.js
Module not found: Error: Can't resolve 'http' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/got'
ERROR in ./node_modules/ical/node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'http' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/http-signature/lib'
ERROR in ./node_modules/ical/node_modules/request/request.js
Module not found: Error: Can't resolve 'http' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request'
ERROR in ./node_modules/ical/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'http' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/tunnel-agent'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'https' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/forever-agent'
ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'https' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/got'
ERROR in ./node_modules/ical/node_modules/request/request.js
Module not found: Error: Can't resolve 'https' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request'
ERROR in ./node_modules/ical/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'https' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/tunnel-agent'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/forever-agent'
ERROR in ./node_modules/ical/node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/tough-cookie/lib'
ERROR in ./node_modules/ical/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/tunnel-agent'
ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/mime-types'
ERROR in ./node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/assert-plus'
ERROR in ./node_modules/clone-response/src/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/clone-response/src'
ERROR in ./node_modules/combined-stream/lib/combined_stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/combined-stream/lib'
ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/delayed-stream/lib'
ERROR in ./node_modules/duplexer3/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/duplexer3'
ERROR in ./node_modules/get-stream/buffer-stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/get-stream'
ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/got'
ERROR in ./node_modules/ical/node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/assert-plus'
ERROR in ./node_modules/ical/node_modules/request/request.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request'
ERROR in ./node_modules/isstream/isstream.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/isstream'
ERROR in ./node_modules/responselike/src/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/responselike/src'
ERROR in ./node_modules/sshpk/lib/ed-compat.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/sshpk/lib'
ERROR in ./node_modules/stringstream/stringstream.js
Module not found: Error: Can't resolve 'stream' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/stringstream'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/forever-agent'
ERROR in ./node_modules/ical/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/tunnel-agent'
ERROR in ./node_modules/ical/node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in '/Users/marcwilson/dev/Headset.Insights/wwwroot/ClientApp/node_modules/ical/node_modules/request'

**Comment by mitica** [comment]
Removed `ical` and `got` dependencies.
Added `cross-fetch`.

Published version 0.2.2.

I didn't test it on react-native or in browser. Hope it helped!
